### PR TITLE
Fix svelte repl urls

### PR DESCRIPTION
**Pull request by nukhtarov**
The old links don't work anymore, so I changed them to the new ones

### CODE REVIEW

**Comment by jonasgeiler** [comment]
I cannot believe that they just killed literally all REPL links all over the web. This is so excruciating...

Anyways, thank you for the PR!

**Comment by jonasgeiler** [comment]
Okay this is very clearly a bug, as reported in sveltejs/svelte.dev#1056

**Comment by nukhtarov** [comment]
I agree. They could have done a redirect

**Comment by jonasgeiler** [comment]
They fixed it now in sveltejs/svelte.dev#1089

**Pull request merged**
